// flow-typed signature: 28eb1834a6ede8a21fc34744b4cca9af
// flow-typed version: <<STUB>>/eslint-config-airbnb-flow_v^1.0.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-airbnb-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-airbnb-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-airbnb-flow/index' {
  declare module.exports: $Exports<'eslint-config-airbnb-flow'>;
}
declare module 'eslint-config-airbnb-flow/index.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-flow'>;
}
