// flow-typed signature: 4e942bafe04b30170893f5083dca52a2
// flow-typed version: <<STUB>>/@shopify/draggable_v^1.0.0-beta.4/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shopify/draggable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shopify/draggable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shopify/draggable/lib/draggable.bundle' {
  declare module.exports: any;
}

declare module '@shopify/draggable/lib/draggable.bundle.legacy' {
  declare module.exports: any;
}

declare module '@shopify/draggable/lib/draggable' {
  declare module.exports: any;
}

declare module '@shopify/draggable/lib/droppable' {
  declare module.exports: any;
}

declare module '@shopify/draggable/lib/plugins' {
  declare module.exports: any;
}

declare module '@shopify/draggable/lib/plugins/collidable' {
  declare module.exports: any;
}

declare module '@shopify/draggable/lib/plugins/snappable' {
  declare module.exports: any;
}

declare module '@shopify/draggable/lib/plugins/swap-animation' {
  declare module.exports: any;
}

declare module '@shopify/draggable/lib/sortable' {
  declare module.exports: any;
}

declare module '@shopify/draggable/lib/swappable' {
  declare module.exports: any;
}

declare module '@shopify/draggable/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shopify/draggable/lib/draggable.bundle.js' {
  declare module.exports: $Exports<'@shopify/draggable/lib/draggable.bundle'>;
}
declare module '@shopify/draggable/lib/draggable.bundle.legacy.js' {
  declare module.exports: $Exports<'@shopify/draggable/lib/draggable.bundle.legacy'>;
}
declare module '@shopify/draggable/lib/draggable.js' {
  declare module.exports: $Exports<'@shopify/draggable/lib/draggable'>;
}
declare module '@shopify/draggable/lib/droppable.js' {
  declare module.exports: $Exports<'@shopify/draggable/lib/droppable'>;
}
declare module '@shopify/draggable/lib/plugins.js' {
  declare module.exports: $Exports<'@shopify/draggable/lib/plugins'>;
}
declare module '@shopify/draggable/lib/plugins/collidable.js' {
  declare module.exports: $Exports<'@shopify/draggable/lib/plugins/collidable'>;
}
declare module '@shopify/draggable/lib/plugins/snappable.js' {
  declare module.exports: $Exports<'@shopify/draggable/lib/plugins/snappable'>;
}
declare module '@shopify/draggable/lib/plugins/swap-animation.js' {
  declare module.exports: $Exports<'@shopify/draggable/lib/plugins/swap-animation'>;
}
declare module '@shopify/draggable/lib/sortable.js' {
  declare module.exports: $Exports<'@shopify/draggable/lib/sortable'>;
}
declare module '@shopify/draggable/lib/swappable.js' {
  declare module.exports: $Exports<'@shopify/draggable/lib/swappable'>;
}
declare module '@shopify/draggable/lib/utils.js' {
  declare module.exports: $Exports<'@shopify/draggable/lib/utils'>;
}
